### ISSUE TITLE
Roi __repr__ does not follow python convention

### ISSUE THREAD

**Issue by anforsm** [funkelab/funlib.geometry#3]
The `Roi.__repr__` method does not follow Python convention of "Return a string containing a printable representation of an object. For many types, this function makes an attempt to return a string that would yield an object with the same value when passed to eval()". See https://docs.python.org/3/library/functions.html#repr.

`__repr__` should return something like `Roi([0, 0, 0], [50, 50, 50])`.

The current `__repr__` implementation would be more representative of `__str__`.

https://github.com/funkelab/funlib.geometry/blob/dc075d401448678487ac4973f69c570d9d4d03a6/funlib/geometry/roi.py#L466-L478

**Comment by pattonw** [comment]
Thanks! I did not know about this distinction. I've pushed a commit to fix this that will be included in the next patch release.
